site_name: vAccel
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - User Guide:
    - vaccelrt.md
    - Plugins:
      - jetson.md
      - virtio.md
      - coral.md
    - run.md
  - kata-vaccel.md
  - k8s:
    - devmapper.md
    - k8s/kata.md
  - Unikernels:
    - unikernels/unikraft.md
  - examples.md
  - usecases.md
  - Developers Guide: 
    - post.md

theme:
  name: material
  #favicon: img/vaccel-logo.png
  logo: img/vaccel-logo.png
 
features:
  - navigation.instant
  - navigation.sections
  - navigation.expand
  - toc.integrate

markdown_extensions:
  - footnotes
  - attr_list

toc:
  - permalink: true

copyright: Copyright &copy; 2018 - 2021 Nubificus LTD

extra_css:
  - stylesheets/extra.css
gtags:
  - G-X2S0PFR6ZY
